---
title: "Rapport"
author: "Victor"
date: "1/22/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#MAP

##DensityMap

```{r}
library(sf)
library(ggplot2)
library(tmap)
library(tmaptools)
library(leaflet)
library(dplyr)

mydata <- readr::read_csv("Density Map/Density per Fylker.csv")

mymap <- st_read("Density Map/NORWAY SHAPE/NOR_adm1.shp", stringsAsFactors = FALSE)

datamap1 <- inner_join(mymap, mydata)

```


```{r}

datamap2 <- ifelse(datamap1$Density >= 0 & datamap1$Density <= 5, "0-5", ifelse(datamap1$Density >= 6 & datamap1$Density <= 10, "6-10", ifelse(datamap1$Density >= 11 & datamap1$Density <= 20, "11-20", ifelse(datamap1$Density >= 21 & datamap1$Density <= 50, "21-50", ifelse(datamap1$Density >= 51 & datamap1$Density <= 100, "51-100", ifelse(datamap1$Density >= 101 & datamap1$Density <= 200, "101-200", ifelse(datamap1$Density >= 201 & datamap1$Density <= 500, "201-500", ifelse(datamap1$Density >= 501, "501+", NA))))))))

```


```{r}

cut(datamap1$Density, breaks=c(0, 5, 10, 20, 50, 100, 200, 500, Inf), labels=c("0-5", "6-10", "11-20", "21-50", "51-100", "101-200","201-500", "500+"))

```

```{r}

mylabels <- c("0-5", "6-10", "11-20", "21-50", "51-100", "101-200", "201-500", "500+")

```


```{r}

datamap1$Density <- base::cut(datamap1$Density,
                        breaks = c(0, 5, 10, 20, 50, 100, 200, 500, 2000), 
                        labels = mylabels, right = F, ordered_result = T)

```


```{r}

tm_shape(datamap1) +
  tm_polygons("Density", id = "NAME_1", palette = "Oranges")+ "Density"
  theme_minimal()
  
tmap_mode("view")
DensityMap <- tmap_last()

tmap_save(DensityMap, "DensityMap.html")


```


#GRAPHS

##Graph1

```{r}
library(spiR)

FOW <- sqs_spi_data(country = c("AUS", "DNK", "NOR", "NLD", "DEU"), 
                       year = c("2014","2015","2016", "2017", "2018", "2019"), 
                       indicators = "FOW")
```


```{r}
library(ggplot2)
library(plotly)

graph1 <- ggplot(FOW) +
 aes(x = var_year, y = value, colour = countryName, group = countryName) +
 geom_line(size = 1.2) +
 scale_color_hue() +
 labs(x = "Year", y = "Wellbeing Indicator", title = "Wellbeing", color = "Countries") +
 theme_minimal() 

graph1 <- ggplotly(graph1)
graph1

```

##Graph2

```{r}

library(spiR)

HWE <- sqs_spi_data(country = c("AUS", "DNK", "NOR", "NLD", "DEU"), 
                       year = c("2014","2015","2016", "2017", "2018", "2019"), 
                       indicators = "HWE")

```

```{r}
library(ggplot2)
library(plotly)

graph2 <- ggplot(HWE) +
 aes(x = var_year, y = value, colour = countryName, group = countryName) +
 geom_line(size = 1.2) +
 scale_color_hue() +
 labs(x = "Year", y = "Health & Wellness Indicator", title = "Health & Wellness", color = "Countries") +
 theme_minimal() 

graph2 <- ggplotly(graph2)
graph2

```

##Graph3

```{r}

library(spiR)

SHE_2 <- sqs_spi_data(country = c("AUS", "DNK", "NOR", "NLD", "DEU"), 
                       year = c("2014","2015","2016", "2017", "2018", "2019"), 
                       indicators = "SHE_2")

```

```{r}
library(ggplot2)
library(plotly)

graph3 <- ggplot(SHE_2) +
 aes(x = var_year, y = value, colour = countryName, group = countryName) +
 geom_line(size = 1.2) +
 scale_color_hue() +
 labs(x = "Year", y = "Electricity Quality Indicator", title = "Electricity Quality", color = "Countries") +
 theme_minimal() 

graph3 <- ggplotly(graph3)
graph3

```



##Graph4

```{r}

library(spiR)

EQU_2 <- sqs_spi_data(country = c("AUS", "DNK", "NOR", "NLD", "DEU"), 
                       year = c("2014","2015","2016", "2017", "2018", "2019"), 
                       indicators = "EQU_2")

#Outdoor air pollution attributable deaths EQU_1

EQU_1 <- sqs_spi_data(country = c("AUS", "DNK", "NOR", "NLD", "DEU"), 
                       year = c("2014","2015","2016", "2017", "2018", "2019"), 
                       indicators = "EQU_1")

EQU_1 <- dplyr::rename(EQU_1, Deaths = value)
EQU_2 <- dplyr::rename(EQU_2, Emissions = value)

EQU_2 <- EQU_2[order(EQU_2$countryName),]
EQU_1 <- EQU_1[order(EQU_1$countryName),]
EQU_2$var_code <- NULL
EQU_2$var_indicator <- NULL
EQU_1$var_code <- NULL
EQU_1$var_indicator <- NULL
EQU_2$var_year <- NULL
EQU_1
EQU_2
EQUFINAL <- dplyr::left_join(EQU_1, EQU_2, by = "countryName")
EQUFINAL 


```


```{r}
library(ggplot2)
library(plotly)

graph4 <- ggplot(EQUFINAL, aes(var_year, value, color = countryName)) +
  geom_point(aes(size = 1, frame = var_year)) +
  scale_x_log10()

graph4 <- ggplotly(graph6)
graph4

```

```{r}
library(ggplot2)
library(plotly)

graph4 <- ggplot(EQUFINAL) +
 aes(x = Deaths, y = Emissions, z = var_year, colour = countryName, group  = countryName) +
 geom_point(size = 1L) +
 scale_z_log10() +
 scale_color_hue() +
 theme_minimal()


graph4 <- ggplotly(graph4)
graph4



```








```{r}
library(ggplot2)
library(plotly)

EQU <- EQU[order(EQU$countryName),]
EQU

graph6 <- ggplot(EQU, aes(var_year, value, color = countryName)) +
  geom_point(aes(size = 1, frame = var_year)) +
  scale_x_log10()

graph6 <- ggplotly(graph6)
graph6

```

##Graph5

```{r}

sqs_spi_indicator()


```



##Graph6

```{r}

library(spiR)

EQU <- sqs_spi_data(country = c("AUS", "DNK", "NOR", "NLD", "DEU"), 
                       year = c("2014","2015","2016", "2017", "2018", "2019"), 
                       indicators = "EQU_2")

```

```{r}
library(ggplot2)
library(plotly)

EQU <- EQU[order(EQU$countryName),]
EQU

graph6 <- ggplot(EQU, aes(var_year, value, color = countryName)) +
  geom_point(aes(size = 1, frame = var_year)) +
  scale_x_log10()

graph6 <- ggplotly(graph6)
graph6

```